#!/bin/bash 

rm -rf  $VERBOSE   LOG_*
rm -rf  $VERBOSE   MOOSLog_*
rm -rf  $VERBOSE   node_*
rm -f   $VERBOSE   *~
rm -f   $VERBOSE   targ_*
rm -f   $VERBOSE   shoreside_log*
rm -f   $VERBOSE   .LastOpenedMOOSLogDirectory

echo "Removed all autogenerated files."

