"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

import cStringIO as StringIO
import struct

class joystick_t(object):
    __slots__ = ["values"]

    def __init__(self):
        self.values = [ 0.0 for dim0 in range(17) ]

    def encode(self):
        buf = StringIO.StringIO()
        buf.write(joystick_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>17d', *self.values[:17]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = StringIO.StringIO(data)
        if buf.read(8) != joystick_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return joystick_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = joystick_t()
        self.values = struct.unpack('>17d', buf.read(136))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if joystick_t in parents: return 0
        tmphash = (0x3b6037c1131fe9a7) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if joystick_t._packed_fingerprint is None:
            joystick_t._packed_fingerprint = struct.pack(">Q", joystick_t._get_hash_recursive([]))
        return joystick_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

